services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: picpay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: